services:
  sporthubnotificationservice:
    image: sporthubnotificationservice
    build:
      context: .
      dockerfile: src/SportHubNotificationService/Dockerfile
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
